name: simple-cache-example

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Remember node_modules from last time
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-cache

      - name: Install packages
        run: npm install
