name: Multiple Needs Example

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Building..."

  test:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Testing..."

  deploy:
    needs:
      - build
      - test

    runs-on: ubuntu-latest

    steps:
      - run: echo "Deploying Application..."
